name: "Coding Standards"

on:
  pull_request:
  push:
    branches:
      - "master"
      - "2.x"
      - "3.x"

jobs:
  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-24.04"

    strategy:
      matrix:
        php-version:
          - "8.4"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"

      - name: "Install dependencies with Composer"
        uses: ibexa/gh-workflows/actions/composer-install@main
        with:
          php-version: "${{ matrix.php-version }}"
          gh-client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
          gh-client-secret: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
          satis-network-key: ${{ secrets.SATIS_NETWORK_KEY }}
          satis-network-token: ${{ secrets.SATIS_NETWORK_TOKEN }}
        env:
          COMPOSER_FUND: '0'

      - name: "Run PHP_CodeSniffer"
        run: "vendor/bin/phpcs"
